#!/usr/bin/env node

'use strict';

var request = require('superagent'),
    debug = require('debug')('client'),
    Listener = require('./lib/listener'),
    commander = require('commander');

commander.version('0.1.0')
    .option('-r, --remote [url]', 'Remote callback server.')
    .option('-k, --key <key>', 'Application key generated by "refresh".')
    .option('-s, --secret <secret>', 'Application secret generated by "refresh".')
    .option('refresh <access token>', 'Get a new the application key.')
    .option('listen', 'Listen and waits for callbacks based on the application key.')
    .parse(process.argv);


/*
 * some global configs
 */
var server = commander.server || 'http://localhost:3001';
debug('Using remote callback server %s', server);

var listener = typeof commander.listen === 'string' ? commander.listen : 'http://localhost:3000';
debug('Using %s to dispatch incoming requests locally.', listener);

var appKey = commander.key;
if (appKey) debug('Using app key "%s".', appKey);

var appSecret = commander.secret;
if (appSecret) debug('Using app secret "%s".', appSecret);


/*
 * actual functionality
 */
function refresh(accessToken) {
    debug('Refresh callback');

    request.get(server + '/credentials').query({'access_token': accessToken}).end(function (error, result) {
        if (error) {
            console.error('Unable to reach the server.', error);
            return;
        }

        console.log('Key:\t%s', result.body.appKey);
        console.log('Secret:\t%s', result.body.appSecret);
    });
}

function listen() {
    listener = new Listener(server, appKey, appSecret);

    listener.on('connect', function () {
        debug('Connected to server "%s".', server);
    });
    listener.on('disconnect', function () {
        debug('Disconnected from server "%s".', server);
    });
    listener.on('callback', function (data) {
        debug('Received callback.');
        console.log(data);
    });
    listener.on('auth_failed', function () {
        console.error('Registering with the provided access token failed.');
        console.log('Try to get a new application token via ./client.js refresh <access token>.');
        process.exit(1);
    });

    listener.start();
}


/*
 * Main program flow starts here
 */
if (commander.listen) {
    if (!appKey || !appSecret) {
        console.error('The listen command needs a --key and a --secret.');
        commander.help();
        return;
    }

    listen();
} else if (commander.refresh) {
    refresh(commander.refresh);
} else {
    commander.help();
}
